### Autograd

In [1]:
import tensorflow as tf

In [3]:
x = tf.constant([1,2,3])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
(3,)
<dtype: 'int32'>


In [4]:
x = tf.Variable([1,2,3])
print(x)
print(x.shape)
print(x.dtype)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
(3,)
<dtype: 'int32'>


In [7]:
# running a gradient tape on a tf variable
# we get the gradient of y = x^2 at x = 3.6
x = tf.Variable(3.6)
with tf.GradientTape() as tape:
    y = x*x
    dy = tape.gradient(y,x)
    print(dy)

tf.Tensor(7.2, shape=(), dtype=float32)


## Using Autograd

In [9]:
# making up a polynomial in numpy
import numpy as np
polynomial = np.poly1d([1,2,3])
print(polynomial)

   2
1 x + 2 x + 3


In [10]:
# creating X and Y which represent this polynomial. 20 values, X is random between 10 and -10
N = 20
X = np.random.uniform(-10,10,size=(N,1))
Y = polynomial(X)

In [13]:
# using the values generated above we try to fit a polynomial
# we assume we already know we need to predict ax2 + bx + c
# so w only has size 3
XX = np.hstack([X*X, X, np.ones_like(X)])

#prepare tensorflow data
w = tf.Variable(tf.random.normal((3,1)))
x = tf.constant(XX, dtype=tf.float32)
y = tf.constant(Y, dtype=tf.float32)
optimizer = tf.keras.optimizers.Nadam(learning_rate=0.01)
print(w)

for _ in range(1000):
    with tf.GradientTape() as tape:
        y_pred = x @ w # @ is used for matrix multiplication and is similar to tf.matmul
        mse = tf.reduce_sum(tf.square(y - y_pred))
    grad = tape.gradient(mse, w)
    optimizer.apply_gradients([(grad, w)])

print(w)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-1.3544159 ],
       [ 0.7045493 ],
       [ 0.03666191]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.0071912],
       [2.0142002],
       [2.5059197]], dtype=float32)>
